name: Build and deploy Laravel app to Azure Web App - msdocs-laravel-mysql-XYZ

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, curl, mysql, zip

      - name: Install Composer Dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          zip -r release.zip . -x "node_modules/*" ".git/*" "tests/*"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip Artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'msdocs-laravel-mysql-XYZ'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
